server:
  port: 9091

spring:
  application:
    name: dubbo-provier

dubbo:
  application:
    name: dubbo-provier
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: cn.knightzz.service.impl
  protocol:
    name: dubbo
    port: 20881