server:
  port: 9090

spring:
  application:
    name: dubbo-provier

dubbo:
  application:
    name: dubbo-consumer # \u6D88\u8D39\u65B9\u5E94\u7528\u540D\uFF0C\u7528\u4E8E\u8BA1\u7B97\u4F9D\u8D56\u5173\u7CFB\uFF0C\u4E0D\u662F\u5339\u914D\u6761\u4EF6\uFF0C\u4E0D\u8981\u4E0E\u63D0\u4F9B\u65B9\u4E00\u6837
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: cn.knightzz.service.impl
  protocol:
    name: dubbo
    port: 20881